SAMS_URL = "https://www.samsclub.com/s/baby%20formula"
COSTCO_URL = "https://www.costco.com/formula-feeding.html"
TARGET_URL = "https://www.target.com/s?searchTerm=powder+infant+formula+"
WALMART_URL = "https://www.walmart.com/browse/feeding/parent-s-choice-baby-formula/5427_133283_9817698"
AMAZON_URL = "https://www.amazon.com/ref=nav_logo"
WALGREENS_URL = "https://www.walgreens.com/store/c/productlist/N=374331-2000014765"
KROGER_URL = "https://www.kroger.com/pl/baby-formula/44008?taxonomyId=44008&brandName=Comforts&fulfillment=all"